name: example
description: Charts-Flutter Demo
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.3.0
  intl: ^0.17.0
flutter:
  uses-material-design: true
